---
output:
  pdf_document:
    latex_engine: lualatex
    toc: false
    toc_depth: 2
    number_sections: TRUE
header-includes:
  - \usepackage{indentfirst}
  - \parindent = 1em
  - \usepackage{dcolumn}
  - \newcolumntype{.}{D{.}{.}{-1}}
  - \usepackage{caption}
  - \captionsetup[table]{name=表}
  - \captionsetup[figure]{name=図}
  - \usepackage{hyperref}
  - \pagestyle{empty}
  - \usepackage{multicol}
  - \usepackage{ascmac}
  - \setpagelayout*{top=10truemm,bottom=10truemm,left=25truemm,right=10truemm}
  - \usepackage{tikz}
  - \usepackage{tabstackengine}
  - \usepackage{xcolor}
  - \usepackage{rotating}
  - \usepackage{txfonts}
  - \usepackage{fancybox}
  - \usepackage{dashbox}
  - \usepackage{tcolorbox}
  - \usepackage{siunitx}
documentclass: bxjsarticle
classoption: 11pt,b4paper,landscape,lualatex,ja=standard
---

```{r global_option, include = FALSE}
knitr::opts_chunk$set(warning = FALSE, 
                      echo = FALSE, 
                      message = FALSE,
                      fig.width = 7,
                      fig.height = 5)
if (knitr::is_latex_output()) {
  knitr::opts_chunk$set(dev = "cairo_pdf")
}
```
\renewcommand{\thefootnote}{}
\newcounter{kaunta}
\renewcommand{\thekaunta}{\arabic{kaunta}}
\newcommand{\kaunta}{\refstepcounter{kaunta}%
\thekaunta}
\def\question{\noindent\fbox{\large\makebox[1em]{\text{\kaunta}}} \hspace{1pt}}
\newcounter{skaunta}
\renewcommand{\theskaunta}{\arabic{skaunta}}
\newcommand{\skaunta}{\refstepcounter{skaunta}%
\theskaunta}
\def\squestion{(\text{\skaunta})\hspace{2.5pt}}

\begin{flushleft}
\noindent
\large
1次式の計算No.2
\end{flushleft}

\begin{flushright}
名前（\hspace{50mm}）
\end{flushright}

\vspace{1mm}
\hrule

1次式の加法は、文字の部分が\fbox{\phantom{同じ}}項どうし、数の項どうしを加えればよい。

\begin{multicols}{2}
例4. $(3a + 2) + (6a -5)$

\vspace{20mm}

問4. 次の計算をしなさい。

(1) $(4a + 5) + (3a - 1)$ \hspace{30mm} (2) $(2x + 5) + (3x - 7)$

\vspace{20mm}

(3) $(5x - 9) + (x - 9)$ \hspace{30mm} (4) $3x + (1 - 4x)$ 

\vspace{20mm}

(5) $(-2a + 7) + (3a -6)$ \hspace{30mm} (6) $(7x - 5) + (-9x + 5)$

\vspace{20mm}

問5. $-x-8$と$4x + 2$の和を求めなさい。

\columnbreak
\begin{itembox}[l]{Q}
$4x - (x - 1)$はどのように計算すればよいでしょうか。
\end{itembox}

数をひくことは、その数の符号を変えてひく加えることと同じである。

1次式の減法も同じように、ひくほうの式の各項の\fbox{\phantom{符号}}を変えて加えればよい。

例5. $(a + 7) - (5a - 3)$

\vspace{20mm}

問6. 次の計算をしなさい。

(1) $(9a + 7) - (2a + 3)$ \hspace{30mm} (2) $(6x - 3) - (4x + 5)$

\vspace{20mm}

(3) $(a + 3) - (2a - 1)$ \hspace{30mm} (4) $(-2a -9) - (b + 2)$

\vspace{20mm}

(5) $(5a - 4) - (4 - 3a)$ \hspace{30mm} (6) $(x - 4) - (-2x - 3)$

\vspace{20mm}
問7. $7x - 3$から$2x -3$をひいた差を求めなさい。

\end{multicols}





































































