---
output:
  pdf_document:
    latex_engine: lualatex
    toc: false
    toc_depth: 2
    number_sections: TRUE
header-includes:
  - \usepackage{indentfirst}
  - \parindent = 1em
  - \usepackage{dcolumn}
  - \newcolumntype{.}{D{.}{.}{-1}}
  - \usepackage{caption}
  - \captionsetup[table]{name=表}
  - \captionsetup[figure]{name=図}
  - \usepackage{hyperref}
  - \pagestyle{empty}
  - \usepackage{multicol}
  - \usepackage{ascmac}
  - \setpagelayout*{top=10truemm,bottom=10truemm,left=25truemm,right=10truemm}
  - \usepackage{tikz}
  - \usepackage{tabstackengine}
  - \usepackage{xcolor}
  - \usepackage{rotating}
  - \usepackage{txfonts}
  - \usepackage{fancybox}
  - \usepackage{dashbox}
  - \usepackage{tcolorbox}
  - \usepackage{siunitx}
documentclass: bxjsarticle
classoption: 11pt,b4paper,landscape,lualatex,ja=standard
---

```{r global_option, include = FALSE}
knitr::opts_chunk$set(warning = FALSE, 
                      echo = FALSE, 
                      message = FALSE,
                      fig.width = 7,
                      fig.height = 5)
if (knitr::is_latex_output()) {
  knitr::opts_chunk$set(dev = "cairo_pdf")
}
```
\renewcommand{\thefootnote}{}
\newcounter{kaunta}
\renewcommand{\thekaunta}{\arabic{kaunta}}
\newcommand{\kaunta}{\refstepcounter{kaunta}%
\thekaunta}
\def\question{\noindent\fbox{\large\makebox[1em]{\text{\kaunta}}} \hspace{1pt}}
\newcounter{skaunta}
\renewcommand{\theskaunta}{\arabic{skaunta}}
\newcommand{\skaunta}{\refstepcounter{skaunta}%
\theskaunta}
\def\squestion{(\text{\skaunta})\hspace{2.5pt}}

\begin{flushleft}
\noindent
\large
1次式の計算
\end{flushleft}

\begin{flushright}
名前（\hspace{50mm}）
\end{flushright}

\vspace{1mm}
\hrule

\begin{multicols}{2}

$1+3x$という式で、加法の記号$+$で結ばれた$1, \, 3x$のそれぞれを\fbox{\phantom{項}}という。

また、$3x$という項で、数の部分3を$x$の\fbox{\phantom{係数}}という。

項には、$3x$のように文字を含む項と、1のように文字を含まない数だけの項がある。

例1. $x -3x$ の項と係数を考えてみよう。

\vspace{30mm}

問1. 次の式の項と、文字をふくむ項の係数をいいなさい。

(1) $4x + y$ \hspace{40mm} (2) $7x - 2y$ \hspace{30mm} \hspace{40mm} 

\vspace{5mm}
\underline{項 \hspace{15mm} 係数 \hspace{15mm}} \hspace{10mm} \underline{項 \hspace{15mm} 係数 \hspace{15mm}}

\vspace{5mm}

(3) $-x + \dfrac{2}{3}y + 5$ \hspace{40mm} (4) $5a - \dfrac{b}{4} - \dfrac{1}{3}$

\vspace{5mm}

\underline{項 \hspace{15mm} 係数 \hspace{15mm}} \hspace{10mm} \underline{項 \hspace{15mm} 係数 \hspace{15mm}}

\vspace{5mm}

式$1 + 3x$の項のうち、$3x$のように、文字が1つだけの項を\fbox{\phantom{1次の項}}という。

1次の項だけか、1次の項と数の項の和で表すことができる式を\fbox{\phantom{1次式}}という。

例2. (1) $3x + 6x$ \hspace{30mm} (2) $3x - 6x$

\vspace{20mm}

問2. 次の計算をしなさい。

(1) $5x + 7x$ \hspace{30mm} (2) $6y - 2y$ \hspace{30mm} (3) $4x - 3x$ 

\vspace{30mm}

(4) $-9a + 6a$ \hspace{30mm} (5) $5y - y$ \hspace{30mm} (6) $-3x -2x$

\vspace{30mm} 

例3. $7x + 3 - 5x -6$

\vspace{30mm}

問3. 次の計算をしなさい。

(1) $8x + 6 -3x -3$ \hspace{30mm} (2) $5x -2 -4x + 8$

\vspace{30mm}

(3) $6x -7 + 3x -2$ \hspace{30mm} (4) $6a -4 -5a + 1$ 

\vspace{30mm} 

(5) $3x -2 + x + 9$ \hspace{30mm} (6) $a + 5 - 7a - 5$






































































\end{multicols}