---
output:
  pdf_document:
    latex_engine: lualatex
    toc: false
    toc_depth: 2
    number_sections: TRUE
header-includes:
  - \usepackage{indentfirst}
  - \parindent = 0pt
  - \usepackage{dcolumn}
  - \newcolumntype{.}{D{.}{.}{-1}}
  - \usepackage{caption}
  - \captionsetup[table]{name=表}
  - \captionsetup[figure]{name=図}
  - \usepackage{hyperref}
  - \pagestyle{empty}
  - \usepackage{multicol}
  - \usepackage{ascmac}
  - \usepackage{tikz}
  - \usepackage{amsmath}
  - \usepackage{amsfonts}
  - \usepackage{latexsym}
  - \usepackage{graphics}
  - \usepackage{here}
documentclass: bxjsarticle
classoption: 12pt,b4paper,landscape,lualatex,ja=standard
---

```{r global_option, include = FALSE}
knitr::opts_chunk$set(warning = FALSE, 
                      echo = FALSE, 
                      message = FALSE,
                      fig.width = 7,
                      fig.height = 5)
if (knitr::is_latex_output()) {
  knitr::opts_chunk$set(dev = "cairo_pdf")
}
```
\renewcommand{\thefootnote}{}

\begin{flushleft}
\noindent
\large
復習No.1
\end{flushleft}

\begin{flushright}
名前（\hspace{50mm}）
\end{flushright}

\vspace{1mm}
\hrule

\begin{multicols}{2}

自然数$\cdots \quad$\fbox{\hskip1em\rule{0pt}{2ex}}以上の整数

素数$\cdots \quad$1と\fbox{\hskip40mm\rule{0pt}{2ex}}の積でしか表せない自然数

問1. 次の数の中から、自然数をすべて選びなさい。

$$
-5, 0, 3, 4.7, 9
$$

\vspace{5mm}

問2. 次の数の中から、素数をすべて選びなさい。

$$
1, 4, 2, 6, 11, 13
$$
\vspace{5mm}

$120=2\times2\times2\times3\times5$のように、自然数を素数だけの積で表すことを\fbox{\hskip45mm\rule{0pt}{2ex}}という。

問3. 次の数を素因数分解せよ。

$6=$ \hspace{30mm} $39=$ \hspace{30mm} $50=$

\vspace{25mm}

$+5$や$+8$のような数を\fbox{\hskip25mm\rule{0pt}{2ex}}といい、$-3.5$や$-5.5$のような数を\fbox{\hskip25mm\rule{0pt}{2ex}}という。

問4. 次の数は正負どちらの数か答えよ。

$0$ \hspace{20mm} $-\frac{1}{3}$ \hspace{20mm} $-10000$ \hspace{20mm} $-0.1$ \hspace{20mm} $+20$

\vspace{18mm}

問5. A、B、Cの身長はそれぞれ下の表のとおりである。

　Bの身長を基準にして、それより高いことを正の数、低いことを負の数で表すことにするとき、それぞれの身長を表しなさい。

\begin{center}
\begin{tabular}{|c||c||c|}
\hline
A & B & C \\
\hline
164cm & 156cm & 149cm \\
\hline
\end{tabular}
\end{center}

(1) A

\vspace{5mm}

(2) B

\vspace{5mm}


(3) C

\vspace{5mm}

数直線上で、ある数に対応する点と原点との距離を、その数の\fbox{\hskip30mm\rule{0pt}{2ex}}という。

問6. 次の数の絶対値をいいなさい。

(1) $+8$ \hspace{15mm} (2) $-10$ \hspace{15mm} (3) $+2.5$ \hspace{15mm} (4) $-\frac{1}{3}$

\vspace{10mm}

問7. 次の各組の数の大小を、不等号を使って表しなさい。

(1) $+3, -5$ \hspace{20mm} (2) $-13, -8$ \hspace{20mm} (3) $+6, -9, 0$

\vspace{10mm}

問8. 次の計算をしなさい。

(1) $(+7) + (-2)$ \hspace{20mm} (2) $(+4) + (+5)$ \hspace{20mm} (3) $(+2) + (-18)$

\vspace{10mm}

(4) $(-13) + (-7)$ \hspace{20mm} (5) $(-12) + (+3)$ \hspace{20mm} (6) $(-8) + (-6)$

\vspace{10mm}

(7) $(+9) + (-9)$ \hspace{20mm} (8) $(-1) + (+1)$ \hspace{20mm} (9) $(-4) + 0$

\vspace{10mm}

2つの正負の数の加法では、加えられる数と加える数を入れかえても和は変わらない。これを加法の\fbox{\hskip20mm\rule{0pt}{2ex}}法則という。

また、数の組み合わせを変えても和は変わらない。これを加法の\fbox{\hskip20mm\rule{0pt}{2ex}}法則という。

問8. 次の計算をしなさい。

(1) $(+5) + (-9) + (-7) + (+6)$

\vspace{15mm}

(2) $(+6) + (-18) + (-6)$

\vspace{15mm}

問9. 次の計算をしなさい。

(1) $(-9) - (-2)$ \hspace{20mm} (2) $(+7) - (-6)$ \hspace{20mm} (3) $(+2) - (+10)$

\vspace{10mm}

(4) $(-4) - (-4)$ \hspace{20mm} (5) $(-4) - (-11)$ \hspace{20mm} (6) $0 - (-3)$

\vspace{10mm}

(7) $(-6) - 0$ \hspace{20mm} (8) $(-4) - (+2)$ \hspace{20mm} (9) $(+12) - (+10)$

\vspace{10mm}

問10. 次の計算をしなさい。

(1) $(+4.8) + (-5.2)$ \hspace{30mm} (2) $(-4) + (+2.6)$

\vspace{15mm}

(3) $(-\frac{1}{5}) + (-\frac{3}{5}$ \hspace{30mm} (4) $(-\frac{5}{8}) + (-\frac{3}{8}) $ 

\vspace{15mm}

(5) $(-\frac{1}{2}) + (+\frac{3}{7})$ \hspace{30mm} (6) $(+\frac{3}{5}) + (-\frac{1}{10})$ 

\vspace{15mm}

(7) $(-0.4) - (+0.2)$ \hspace{30mm} (8) $(-3) - (-1.2)$ 

\vspace{15mm} 

(9) $(-\frac{1}{9}) - (-\frac{4}{9})$ \hspace{30mm} (10) $(-\frac{3}{2}) - (-\frac{2}{3})$ 

\vspace{15mm}

\end{multicols}













































