---
output:
  pdf_document:
    latex_engine: lualatex
    toc: false
    toc_depth: 2
    number_sections: TRUE
header-includes:
  - \usepackage{indentfirst}
  - \parindent = 1em
  - \usepackage{dcolumn}
  - \newcolumntype{.}{D{.}{.}{-1}}
  - \usepackage{caption}
  - \captionsetup[table]{name=表}
  - \captionsetup[figure]{name=図}
  - \usepackage{hyperref}
  - \pagestyle{empty}
  - \setpagelayout*{top=10truemm,bottom=10truemm,left=10truemm,right=10truemm}
  - \usepackage{multicol}
  - \usepackage{ascmac}
  - \usepackage{answerbox}
documentclass: bxjsarticle
classoption: 11pt,a4paper,lualatex,ja=standard
---
```{r global_option, include = FALSE}
knitr::opts_chunk$set(warning = FALSE, 
                      echo = FALSE, 
                      message = FALSE,
                      fig.width = 7,
                      fig.height = 5)
if (knitr::is_latex_output()) {
  knitr::opts_chunk$set(dev = "cairo_pdf")
}
```
\renewcommand{\thefootnote}{}
\newcounter{kaunta}
\renewcommand{\thekaunta}{\arabic{kaunta}}
\newcommand{\kaunta}{\refstepcounter{kaunta}%
\thekaunta}
\def\question{\noindent\fbox{\large\makebox[1em]{\text{\kaunta}}} \hspace{1pt}}
\newcounter{skaunta}
\renewcommand{\theskaunta}{\arabic{skaunta}}
\newcommand{\skaunta}{\refstepcounter{skaunta}%
\theskaunta}
\def\squestion{(\text{\skaunta})\hspace{2.5pt}}
\newcommand{\maru}[1]{\raise0.2ex\hbox{\textcircled{\scriptsize{#1}}}}

\answerbox{Swidth=10mm}

\large
2年生数学科1学期期末テスト 解答用紙

\begin{flushright}
組(\hspace{5mm})\hspace{1pt}番号(\hspace{5mm})\hspace{1pt}名前(\hspace{50mm})
\end{flushright}
\hrule

\begin{ansbox}
\pbox[3]{8}
\end{ansbox}

\begin{multicols}{2}
\begin{ansbox}
\pbox*{1}
\end{ansbox}

\begin{ansbox}
\pbox*{1}
\end{ansbox}
\end{multicols}

\begin{multicols}{2}
\begin{ansbox}
\pbox{1}
\pbox{1}
\pbox{1}
\end{ansbox}
\columnbreak
\begin{ansbox*}
\pbox{1}[height=60mm,shoumon=4]
\ptxt{4}{c}{%
\begin{tikzpicture}
\draw[help lines,step=5mm,densely dotted,color=black] (-3.5,-2.4) grid (3.5,3.2);
\draw(-3.5,0)--(3.5,0)node[below]{$x$};
\draw(0,-2.4)--(0,3.2) node[right]{$y$};
\draw(2.5,0)node[below] {5};
\draw(0,2.5)node[right] {5};
\draw(0,0)node[below left]{O};
\end{tikzpicture}}
\end{ansbox*}
\end{multicols}

\begin{multicols}{2}
\begin{ansbox}
\pbox*{1}
\ptxt{1}{l}{列車の長さ}
\ptxt{1}{c}{時速}
\end{ansbox}

\begin{ansbox}
\pbox*{1}
\ptxt{1}{l}{つる}
\ptxt{1}{c}{かめ}
\end{ansbox}
\end{multicols}

\begin{ansbox}
\sxchg{(2)}{\text{\maru{2}}}
\sxchg{(3)}{\text{\maru{3}}}
\pbox{3}
\ptxt{1}{l}{\text{\maru{1}}}
\schg{(1)}
\pbox{2}[shoumon=2]
\end{ansbox}

\begin{ansbox}
\pbox*{1}
\end{ansbox}

\vfill

\begin{flushright}
\begin{tabular}{@{}r}
\begin{tikzpicture}
  \draw (-.5, 0) rectangle (2.5, 2);
  \draw (2.5, 0) rectangle (5.5, 2);
  \draw (5.5, 0) rectangle (9, 2);
  \draw (1, -0.3) node[inner sep=1pt, fill=white]{知・技};
  \draw (4, -0.3) node[inner sep=1pt, fill=white]{思・判・表};
  \draw (7.2, -0.3) node[inner sep=1pt, fill=white]{合計};
\end{tikzpicture}
\end{tabular}
\end{flushright}