---
output:
  pdf_document:
    latex_engine: lualatex
    toc: false
    toc_depth: 2
    number_sections: TRUE
header-includes:
  - \usepackage{indentfirst}
  - \parindent = 0pt
  - \usepackage{dcolumn}
  - \newcolumntype{.}{D{.}{.}{-1}}
  - \usepackage{caption}
  - \captionsetup[table]{name=表}
  - \captionsetup[figure]{name=図}
  - \usepackage{hyperref}
  - \pagestyle{empty}
  - \usepackage{multicol}
  - \usepackage{ascmac}
documentclass: bxjsarticle
classoption: 12pt,b4paper,landscape,lualatex,ja=standard
---

```{r global_option, include = FALSE}
knitr::opts_chunk$set(warning = FALSE, 
                      echo = FALSE, 
                      message = FALSE,
                      fig.width = 7,
                      fig.height = 5)
if (knitr::is_latex_output()) {
  knitr::opts_chunk$set(dev = "cairo_pdf")
}
```
\renewcommand{\thefootnote}{}
\newcounter{kaunta}
\renewcommand{\thekaunta}{\arabic{kaunta}}
\newcommand{\kaunta}{\refstepcounter{kaunta}%
\thekaunta}
\def\question{\noindent\fbox{\large\makebox[1em]{\text{\kaunta}}} \hspace{1pt}}
\newcounter{skaunta}
\renewcommand{\theskaunta}{\arabic{skaunta}}
\newcommand{\skaunta}{\refstepcounter{skaunta}%
\theskaunta}
\def\squestion{(\text{\skaunta})\hspace{2.5pt}}


\begin{flushleft}
\noindent
\large
テスト対策
\end{flushleft}

\begin{flushright}
名前（\hspace{50mm}）
\end{flushright}

\vspace{1mm}
\hrule

\begin{multicols}{2}
\question 次の多項式は何次式ですか。

\squestion $-x^2 + 4y + 3$ \hspace{10mm} \squestion $a -b +5$ \hspace{10mm} \squestion $xy - 2$

\vspace{5mm}

\setcounter{skaunta}{0}

\question 次の同類項をまとめなさい。

\squestion $3x -7y + 4x$ \hspace{30mm} \squestion $8a -b -7a +2b$

\vspace{15mm}

\squestion $-5x + 9y +3x -8y$ \hspace{30mm} \squestion $3x^2 -5x -2x^2 + x$ 

\vspace{15mm}

\squestion $8a^2 -5a -2 +7a$ \hspace{30mm} \squestion $4x -2y -7 + 2x$

\vspace{15mm}

\setcounter{skaunta}{0}

\question 次の2つの多項式をたしなさい。また、左の式から右の式をひきなさい。

\squestion $8x -7y, \, 2x +5y$ \hspace{30mm} \squestion $3a+2b, \, a -4b$

\vspace{30mm}

\squestion $x-4y, \, -2x +3y$

\vspace{30mm}

\setcounter{skaunta}{0}

\question 次の計算をしなさい。

\squestion $\dfrac{2}{5}(10x + 25y)$ \hspace{30mm} \squestion $(8a -12b) \div 4$

\vspace{15mm}

\squestion $(2x -4y) \div \dfrac{2}{3}$ \hspace{30mm} \squestion $7(a -b) - (4a + 6b)$

\vspace{15mm}

\squestion $-4(x +2y) + 3(x + 5y)$ 

\vspace{20mm}

\squestion $3\biggl(4x - \dfrac{1}{3}y \biggl) -6(2x -3y)$

\vspace{20mm}

\squestion $\dfrac{1}{5}(2x + 3y) + \dfrac{1}{3}(5x -2y -1)$ 

\vspace{20mm}

\squestion $\dfrac{5x - 2y}{3} - \dfrac{-3x +  7y}{4}$

\vspace{20mm}

\squestion $5x \times (-2x)$ \hspace{30mm} \squestion $12m \div 2m$

\vspace{15mm} 

\squestion $(-4x)^2$ \hspace{30mm} \squestion $\dfrac{2}{3}xy \times \dfrac{1}{4}x$ 

\vspace{15mm}

\squestion $\dfrac{2}{5}x \times (-10 y^2)$ \hspace{30mm} \squestion $\dfrac{5}{6}x^3\div \biggl( -\dfrac{10}{3}x \biggl)$

\vspace{20mm}

$18xy \div (-3x) \times (-9xy)$ \hspace{30mm} $-12a^2 \div (-6a) \div 2a$

\setcounter{skaunta}{0}

\question $a = 3, \, b = -\dfrac{1}{2}$のとき、次の式の値を求めなさい。

\squestion $2a - 7b -a +3b$ \hspace{30mm} \squestion $3(a -2b) - (5a +2b)$

\vspace{30mm}

\squestion 等式$7x + 4y = 4$を$y$について解きなさい。また、等式$7x + y =4$を$x$について解きなさい。

\vspace{20mm}

\setcounter{skaunta}{0}

\question 次の等式を[]内の文字について解きなさい。

\squestion $y = ax$\hspace{1pt}[$a$] \hspace{15mm} \squestion $l = 2 \pi r$ \hspace{1pt} [$r$]

\vspace{20mm}

\squestion $x + y = 6$ \hspace{1pt} [$x$] \hspace{15mm} \squestion $2x -y = 3$ \hspace{1pt} [y]

\vspace{20mm}

\squestion $l = 2(a + b)$ \hspace{1pt} [$a$] \hspace{15mm} \squestion $4x + 2y = 1$ \hspace{1pt}[$y$]





































\end{multicols}














































































































