---
output:
  pdf_document:
    latex_engine: lualatex
    toc: false
    toc_depth: 2
    number_sections: TRUE
header-includes:
  - \usepackage{indentfirst}
  - \parindent = 1em
  - \usepackage{dcolumn}
  - \newcolumntype{.}{D{.}{.}{-1}}
  - \usepackage{caption}
  - \captionsetup[table]{name=表}
  - \captionsetup[figure]{name=図}
  - \usepackage{hyperref}
  - \pagestyle{empty}
  - \usepackage{multicol}
  - \usepackage{ascmac}
  - \setpagelayout*{top=15truemm}
  - \usepackage{tikz}
  - \usepackage{tabstackengine}
  - \usepackage{xcolor}
  - \usepackage{rotating}
  - \usepackage{txfonts}
  - \usepackage{fancybox}
  - \usepackage{dashbox}
  - \usepackage{tcolorbox}
documentclass: bxjsarticle
classoption: 11pt,b4paper,landscape,lualatex,ja=standard
---

```{r global_option, include = FALSE}
knitr::opts_chunk$set(warning = FALSE, 
                      echo = FALSE, 
                      message = FALSE,
                      fig.width = 7,
                      fig.height = 5)
if (knitr::is_latex_output()) {
  knitr::opts_chunk$set(dev = "cairo_pdf")
}
```
\renewcommand{\thefootnote}{}
\newcounter{kaunta}
\renewcommand{\thekaunta}{\arabic{kaunta}}
\newcommand{\kaunta}{\refstepcounter{kaunta}%
\thekaunta}
\def\question{\noindent\fbox{\large\makebox[1em]{\text{\kaunta}}} \hspace{1pt}}
\newcounter{skaunta}
\renewcommand{\theskaunta}{\arabic{skaunta}}
\newcommand{\skaunta}{\refstepcounter{skaunta}%
\theskaunta}
\def\squestion{(\text{\skaunta})\hspace{2.5pt}}

\begin{flushleft}
\noindent
\large
連立方程式の練習
\end{flushleft}

\begin{flushright}
名前（\hspace{50mm}）
\end{flushright}

\vspace{1mm}
\hrule

\begin{multicols}{2}
\question 次の連立方程式を加減法で解きなさい。

\squestion 
$
\left\{
\begin{array}{l}
5x - 3y = 1 \\
2x + 3y = 13
\end{array}
\right.
$
\vspace{20mm}

\squestion
$
\left\{
\begin{array}{l}
3x + 5y = 19 \\
4x + y = -3
\end{array}
\right.
$

\vspace{20mm}
\squestion
$
\left\{
\begin{array}{l}
-2x + 5y = 18 \\
-4x + 7y = 24
\end{array}
\right.
$
\vspace{20mm}

\squestion
$
\left\{
\begin{array}{l}
3x + 2y = 7 \\
2x - 3y = 9
\end{array}
\right.
$

\vspace{20mm}

\setcounter{skaunta}{0}

\question 次の連立方程式を代入法で解きなさい。

\squestion
$
\left\{
\begin{array}{l}
5x - 4y = -13 \\
y = 3x - 2
\end{array}
\right.
$

\vspace{20mm}

\squestion
$
\left\{
\begin{array}{l}
x = - 2y - 3 \\
2x + y = 6
\end{array}
\right.
$

\setcounter{skaunta}{0}
\vspace{20mm}
\question 次の連立方程式を解きなさい。

\squestion
$
\left\{
\begin{array}{l}
x - 5y = 28 \\
2x + y = 1
\end{array}
\right.
$

\vspace{20mm}
\squestion
$
\left\{
\begin{array}{l}
y = -2x -8 \\
y = 5x + 6
\end{array}
\right.
$

\vspace{20mm}
\squestion
$
\left\{
\begin{array}{l}
3x -4y = 27 \\
5(x + y) = -7y -11
\end{array}
\right.
$

\vspace{20mm}
\squestion
$
\left\{
\begin{array}{l}
2x + 0.3y = 0.4 \\
y = -x + 7
\end{array}
\right.
$

\vspace{20mm}
\squestion
$
\left\{
\begin{array}{l}
0.25x + 0.5y = 2 \\
\dfrac{3}{2} - \dfrac{1}{3}y = -8
\end{array}
\right.
$

\vspace{20mm}
\squestion $5x + y = 10 -3y = 3x -y$
\vspace{30mm}

\squestion
$
\left\{
\begin{array}{l}
\dfrac{x}{6} + \dfrac{y}{2} = 3 \\
3x - 5y = 12
\end{array}
\right.
$

\vspace{20mm}
\squestion
$
\left\{
\begin{array}{l}
0.1x + 0.4y = 0.4 \\
2(x - 3y) + 5y = -10
\end{array}
\right.
$

\vspace{20mm}
\squestion
$4x + 5y = -3x + y = 19$

\vspace{30mm}






\columnbreak

\vspace{10mm}



\end{multicols}





























































