---
output:
  pdf_document:
    latex_engine: lualatex
    toc: false
    toc_depth: 2
    number_sections: TRUE
header-includes:
  - \usepackage{indentfirst}
  - \parindent = 0em
  - \usepackage{dcolumn}
  - \newcolumntype{.}{D{.}{.}{-1}}
  - \usepackage{caption}
  - \captionsetup[table]{name=表}
  - \captionsetup[figure]{name=図}
  - \usepackage{hyperref}
  - \pagestyle{empty}
  - \usepackage{multicol}
  - \usepackage{ascmac}
  - \setpagelayout*{top=10truemm,bottom=20truemm,left=25truemm,right=10truemm}
  - \usepackage{tikz}
  - \usepackage{tabstackengine}
  - \usepackage{xcolor}
  - \usepackage{rotating}
  - \usepackage{txfonts}
  - \usepackage{fancybox}
  - \usepackage{dashbox}
  - \usepackage{tcolorbox}
  - \usepackage{siunitx}
documentclass: bxjsarticle
classoption: 11pt,a4paper,lualatex,ja=standard
---

```{r global_option, include = FALSE}
knitr::opts_chunk$set(warning = FALSE, 
                      echo = FALSE, 
                      message = FALSE,
                      fig.width = 7,
                      fig.height = 5)
if (knitr::is_latex_output()) {
  knitr::opts_chunk$set(dev = "cairo_pdf")
}
```
\renewcommand{\thefootnote}{}
\newcounter{kaunta}
\renewcommand{\thekaunta}{\arabic{kaunta}}
\newcommand{\kaunta}{\refstepcounter{kaunta}%
\thekaunta}
\def\question{\noindent\fbox{\large\makebox[1em]{\text{\kaunta}}} \hspace{1pt}}
\newcounter{skaunta}
\renewcommand{\theskaunta}{\arabic{skaunta}}
\newcommand{\skaunta}{\refstepcounter{skaunta}%
\theskaunta}
\def\squestion{(\text{\skaunta})\hspace{2.5pt}}

\begin{flushleft}
\noindent
\large
計算練習
\end{flushleft}

\begin{flushright}
名前（\hspace{50mm}）
\end{flushright}

\vspace{1mm}
\hrule

\question 次の計算をしなさい。

\begin{multicols}{2}

\squestion $(a + 4)^2$

\squestion $(x - 9)^2$

\end{multicols}
\vfill

\begin{multicols}{2}
\squestion $(a - 6)^2$

\squestion $\biggl(x - \dfrac{1}{5} \biggl)^2$

\end{multicols}
\vfill

\begin{multicols}{2}
\squestion $(x + y)^2$

\squestion $(-x - 7)^2$

\end{multicols}
\vfill

\begin{multicols}{2}

\squestion $(x + 8)(x - 8)$

\squestion $(x - 4)(x + 4)$

\end{multicols}
\vfill

\begin{multicols}{2}
\squestion $\biggl(x + \dfrac{3}{2} \biggl) \biggl(x - \dfrac{3}{2} \biggl)$

\squestion $(10 + a)(10 - a)$

\end{multicols}
\vfill

\begin{multicols}{2}

\squestion $(x + y)(x - y)$

\squestion $(6 - y)(6 + y)$

\end{multicols}

\vfill








































