---
output:
  pdf_document:
    latex_engine: lualatex
    toc: false
    toc_depth: 2
    number_sections: TRUE
header-includes:
  - \usepackage{indentfirst}
  - \parindent = 0pt
  - \usepackage{dcolumn}
  - \newcolumntype{.}{D{.}{.}{-1}}
  - \usepackage{caption}
  - \captionsetup[table]{name=表}
  - \captionsetup[figure]{name=図}
  - \usepackage{hyperref}
  - \pagestyle{empty}
  - \usepackage{multicol}
  - \usepackage{ascmac}
documentclass: bxjsarticle
classoption: 12pt,b4paper,landscape,lualatex,ja=standard
---

```{r global_option, include = FALSE}
knitr::opts_chunk$set(warning = FALSE, 
                      echo = FALSE, 
                      message = FALSE,
                      fig.width = 7,
                      fig.height = 5)
if (knitr::is_latex_output()) {
  knitr::opts_chunk$set(dev = "cairo_pdf")
}
```
\renewcommand{\thefootnote}{}

\begin{flushleft}
\noindent
\large
多項式の乗法 No.1
\end{flushleft}

\begin{flushright}
名前（\hspace{50mm}）
\end{flushright}

\vspace{1mm}
\hrule

\begin{multicols}{2}

\begin{itembox}[l]{展開の公式}
\begin{align*}
  (x + a)(x + b) &= x^2 + (a + b)x + ab \\
  (x + a)^2 &= x^2 + 2ax + a^2 \\
  (x - a)^2 &= x^2 - 2ax + a^2 \\
  (x + a)(x - a) &= x^2 - a^2
\end{align*}
\end{itembox}

教科書pp.15 - 例3 

$(a + 3)(a + 2b - 4)$
\vspace{20mm}

問3. 次の式を展開しなさい。

(1) $(a + 1)(a - b + 2)$ \hspace{30mm} (2) $(2x + y - 1)(5x - 3y)$

\vspace{25mm}

教科書pp.17

例2. $(x + 2)(x + 7)$ を展開してみよう。

\vspace{20mm}

問1. 次の式を公式1の$a$と$b$にあたる数を考えて展開しなさい。

(1) $(x + 3)(x + 6)$ \hspace{30mm} (2) $(x + 1)(x - 3)$

\vspace{20mm}

問2. 次の式を展開しなさい。

(1) $(x + 1)(x + 2)$ \hspace{30mm} (2) $(x + 6)(x - 2)$

\vspace{25mm}

(3) $(x - 3)(x - 4)$ \hspace{30mm} (4) $(y + 3)(y + 5)$

\vspace{25mm}

(5) $(a - 8)(a - 7)$ \hspace{30mm} (6) $(x - 6) (x + 5)$

\vspace{25mm}

(7) $(x - 0.2)(x + 0.4)$ \hspace{30mm} (8) $(y - \frac{2}{3})(y + \frac{1}{3})$
\vspace{25mm}

\end{multicols}


\begin{flushleft}
\noindent
\large
多項式の乗法 No.2
\end{flushleft}

\begin{flushright}
名前（\hspace{50mm}）
\end{flushright}

\vspace{1mm}
\hrule

\begin{multicols}{2}

教科書pp.18 - 例3

(1) $(x + 3)^2$を展開してみよう。

\vspace{20mm}

(2) $(x - 8)^2$を展開してみよう。

\vspace{20mm}

問3. 次の式を展開しなさい。

(1) $(x + 6)^2$ \hspace{30mm} (2) $(a + 9)^2$ 

\vspace{25mm}

(3) $(x - 5)^2$ \hspace{30mm} (4) $(y - 7)^2$

\vspace{25mm}

(5) $(x + \frac{1}{3})^2$ \hspace{30mm} (6) $(a - b)^2$

\vspace{25mm}

教科書pp.19 - 例4

$(x + 6)(x - 6)$を展開してみよう。

\vspace{20mm}

問4. 次の式を展開しなさい。

(1) $(x + 3)(x - 3)$ \hspace{30mm} (2) $(x - 5)(x + 5)$

\vspace{25mm}

(3) $(x + \frac{1}{3})(x - \frac{1}{3})$ \hspace{30mm} (4) $(2 + x)(2 - x)$

\vspace{25mm} 

(5) $(a + b)(a - b)$

\vspace{25mm}

\end{multicols}
\newpage

\begin{flushleft}
\noindent
\large
多項式の乗法 No.3
\end{flushleft}

\begin{flushright}
名前（\hspace{50mm}）
\end{flushright}

\vspace{1mm}
\hrule

\begin{multicols}{2}

問5. 次の式を展開しなさい。

(1) $(x - 4)^2$ \hspace{30mm} (2) $(x - 6)(x + 4)$ 

\vspace{25mm}

(3) $(x + 7)(x - 7)$ \hspace{30mm} (4) $(a + b)^2$ 

\vspace{25mm}

(5) $(x + 6)(x + 2)$ \hspace{30mm} (6) $(8 + a)^2$

\vspace{25mm}

(7) $(a - 2)(a + 5)$ \hspace{30mm} (8) $(x - 9)(9 + x)$

\vspace{25mm}

教科書pp.20 - Q

$(2x + 1)(2x + 3)$を展開してみましょう。

\columnbreak

問6. 次の式を展開しなさい。

(1) $(3x - 4)(3x - 2)$ \hspace{30mm} (2) $(-4a + 3)(-4a - 6)$

\vspace{25mm}

例5. $(2x - 3y)^2$を展開しなさい。

\vspace{20mm}

問7. 次の式を展開しなさい。

(1) $(5x + 2)^2$ \hspace{30mm} (2) $(3x - 4y)^2$

\vspace{25mm}

(3) $(6x + 7)(6x - 7)$ \hspace{30mm} (4) $(7a - 4b)(7a + 4b)$

\vspace{25mm}

\end{multicols}





















































