---
output:
  pdf_document:
    latex_engine: lualatex
    toc: false
    toc_depth: 2
    number_sections: TRUE
header-includes:
  - \usepackage{indentfirst}
  - \parindent = 0pt
  - \usepackage{dcolumn}
  - \newcolumntype{.}{D{.}{.}{-1}}
  - \usepackage{caption}
  - \captionsetup[table]{name=表}
  - \captionsetup[figure]{name=図}
  - \usepackage{hyperref}
  - \pagestyle{empty}
  - \usepackage{multicol}
  - \usepackage{ascmac}
documentclass: bxjsarticle
classoption: 12pt,b4paper,landscape,lualatex,ja=standard
---

```{r global_option, include = FALSE}
knitr::opts_chunk$set(warning = FALSE, 
                      echo = FALSE, 
                      message = FALSE,
                      fig.width = 7,
                      fig.height = 5)
if (knitr::is_latex_output()) {
  knitr::opts_chunk$set(dev = "cairo_pdf")
}
```
\renewcommand{\thefootnote}{}

\begin{flushleft}
\noindent
\large
因数分解 No.1
\end{flushleft}

\begin{flushright}
名前（\hspace{50mm}）
\end{flushright}

\vspace{1mm}
\hrule

\begin{multicols}{2}

\begin{itembox}[l]{公式1}
\begin{align}
x^2 + (a + b)x + ab = (x + a)(x + b)
\end{align}
\end{itembox}

教科書pp26 - 例1

$x^2 + 5x + 6$を因数分解してみよう。

\vspace{15mm}

問1. 次の式を因数分解しなさい。

(1) $x^2 + 7x + 10$ \hspace{30mm} (2) $x^2 + 7x + 6$

\vspace{20mm}

(3) $x^2 + 8x + 12$ \hspace{30mm} (4) $x^2 + 9x + 8$

\vspace{20mm}

例2. $x^2 + x - 6$を因数分解してみよう。

\vspace{15mm}

問2＆問3. 次の式を因数分解しなさい。

(1) $x^2 -2x -15$ \hspace{30mm} (2) $x^2 -2x -8$

\vspace{20mm}

(3) $x^2 +3x -10$ \hspace{30mm} (4) $a^2 -7a -8$

\vspace{20mm}

(1) $x^2 + 10x +9$ \hspace{30mm} (2) $y^2 +5y -36$

\vspace{20mm}

(3) $x^2 -3x -28$ \hspace{30mm} (4) $x^2 -16x +28$

\vspace{20mm}

(5) $x^2 +x -2$ \hspace{30mm} (6) $x^2 + 101x + 100$

\end{multicols}

\newpage

\begin{flushleft}
\noindent
\large
因数分解 No.2
\end{flushleft}

\begin{flushright}
名前（\hspace{50mm}）
\end{flushright}

\vspace{1mm}
\hrule

\begin{multicols}{2}

\begin{itembox}[l]{公式2, 3, 4}
\begin{align}
x^2 + 2ax + a^2 = (x + a)^2\\
x^2 - 2ax + a^2 = (x - a)^2\\
x^2 - a^2 = (x + a)(x - a)
\end{align}
\end{itembox}

例3. $x^2 + 10x +25$を因数分解してみよう。

\vspace{15mm}

問4. 次の式を因数分解しなさい。

(1) $x^2 +12x +36$ \hspace{30mm} (2) $x^2 +4x +4$

\vspace{20mm}

(3) $a^2 +18a +81$ \hspace{30mm} (4) $x^2 -2x +1$

\vspace{20mm}

(5) $y^2 -14y +49$ \hspace{30mm} (6) $x^2 -16x +64$

\vspace{20mm}

例4. $x^2 - 25$

\vspace{15mm}

問5＆問6. 次の式を因数分解しなさい。

(1) $x^2 -36$ \hspace{30mm} (2) $a^2 - 4$

\vspace{20mm}

(3) $x^2 - 1$ \hspace{30mm} (4) $16 - y^2$

\vspace{20mm}

(1) $x^2 -3x +2$ \hspace{30mm} (2) $x^2 -64$

\vspace{20mm}

(3) $y^2 -4y +4$ \hspace{30mm} (4) $y^2 -4y +4$

\vspace{20mm}

(5) $x^2 +13x +36$ \hspace{30mm} (6) $a^2 +22a +121$

\end{multicols}

\newpage

\begin{flushleft}
\noindent
\large
因数分解 No.3
\end{flushleft}

\begin{flushright}
名前（\hspace{50mm}）
\end{flushright}

\vspace{1mm}
\hrule

\begin{multicols}{2}
例5. $2x^2 +4x -16$

\vspace{15mm}

問8. 次の式を因数分解しなさい。

(1) $2x^2 +16x +24$ \hspace{30mm} (2) $-3y^2 +18y -27$

\vspace{20mm}

例6. (1) $4x^2 +4x +1$ \hspace{30mm} (2) $9x^2 -4$





\end{multicols}





























