---
output:
  pdf_document:
    latex_engine: lualatex
    toc: false
    toc_depth: 2
    number_sections: TRUE
header-includes:
  - \usepackage{indentfirst}
  - \parindent = 1em
  - \usepackage{dcolumn}
  - \newcolumntype{.}{D{.}{.}{-1}}
  - \usepackage{caption}
  - \captionsetup[table]{name=表}
  - \captionsetup[figure]{name=図}
  - \usepackage{hyperref}
  - \pagestyle{empty}
  - \usepackage{multicol}
  - \usepackage{ascmac}
  - \setpagelayout*{top=10truemm,bottom=40truemm,left=25truemm,right=10truemm}
  - \usepackage{tikz}
  - \usepackage{tabstackengine}
  - \usepackage{xcolor}
  - \usepackage{rotating}
  - \usepackage{txfonts}
  - \usepackage{fancybox}
  - \usepackage{dashbox}
  - \usepackage{tcolorbox}
  - \usepackage{siunitx}
documentclass: bxjsarticle
classoption: 11pt,b4paper,landscape,lualatex,ja=standard
---

```{r global_option, include = FALSE}
knitr::opts_chunk$set(warning = FALSE, 
                      echo = FALSE, 
                      message = FALSE,
                      fig.width = 7,
                      fig.height = 5)
if (knitr::is_latex_output()) {
  knitr::opts_chunk$set(dev = "cairo_pdf")
}
```
\renewcommand{\thefootnote}{}
\newcounter{kaunta}
\renewcommand{\thekaunta}{\arabic{kaunta}}
\newcommand{\kaunta}{\refstepcounter{kaunta}%
\thekaunta}
\def\question{\noindent\fbox{\large\makebox[1em]{\text{\kaunta}}} \hspace{1pt}}
\newcounter{skaunta}
\renewcommand{\theskaunta}{\arabic{skaunta}}
\newcommand{\skaunta}{\refstepcounter{skaunta}%
\theskaunta}
\def\squestion{(\text{\skaunta})\hspace{2.5pt}}

\begin{flushleft}
\noindent
\large
テスト対策
\end{flushleft}

\begin{flushright}
名前（\hspace{50mm}）
\end{flushright}

\vspace{1mm}
\hrule

\begin{multicols}{2}

\question 次の数の平方根をいいなさい。

(1) 100 \hspace{20mm} (2) 0.04 \hspace{20mm} (3) $\dfrac{25}{49}$

\vspace{20mm}

\question 次の数を$\sqrt{\phantom{aa}}$を使わずに表しなさい。

(1) $\sqrt{36}$ \hspace{20mm} (2) $-\sqrt{0.64}$ \hspace{20mm} (3) $\sqrt{\dfrac{16}{25}}$

\vspace{20mm}

\question 次の各組の数の大小を、不等号を使って表しなさい。

(1) $3, \, \sqrt{7}$ \hspace{20mm} (2) $-\sqrt{5}, \, -\sqrt{6}$

\vspace{20mm}

\question 次の数を、有理数と無理数に分けなさい。
$$
0.2, \, -\sqrt{100}, \, \pi, \, -8, \, -\sqrt{3}, \, \dfrac{1}{9}
$$

\question 次の計算をしなさい。

(1) $\sqrt{5} \times \sqrt{3}$ \hspace{20mm} (2) $\sqrt{2} \times (- \sqrt{11})$

\vspace{15mm}

(3) $\sqrt{6} \div \sqrt{2}$ \hspace{20mm} (4) $(- \sqrt{10}) \div \sqrt{5}$

\vspace{20mm}

\question 次の数を$\sqrt{a}$の形にしなさい。

(1) $4\sqrt{6}$ \hspace{20mm} (2) $\dfrac{\sqrt{5}}{2}$ \hspace{20mm} (3) $9\sqrt{3}$

\vspace{15mm}

\question 次の数の$\sqrt{\phantom{aa}}$の中をできるだけ簡単な数にしなさい。

(1) $\sqrt{75}$ \hspace{20mm} (2) $\sqrt{\dfrac{7}{9}}$

\vspace{20mm}

\question 次の数の分母を有理化しなさい。

(1) $\dfrac{1}{\sqrt{5}}$ \hspace{20mm} (2) $\dfrac{5}{2\sqrt{3}}$

\vspace{20mm}

\question $\sqrt{2} \, = \, 1.414$として、次の値を求めなさい。

(1) $\sqrt{8}$ \hspace{20mm} (2) $\sqrt{200}$ \hspace{20mm} (3) $\sqrt{\dfrac{1}{50}}$


\vspace{20mm}

\question 次の計算をしなさい。

(1) $2\sqrt{3} + \sqrt{3}$  \hspace{30mm} (2) $3\sqrt{5} + \sqrt{2} - \sqrt{5}$

\vspace{20mm}

(3) $\sqrt{45} + \sqrt{5}$ \hspace{30mm} (4) $\sqrt{50} - \sqrt{32}$

\vspace{20mm}

\question 次の計算をしなさい。

(1) $\sqrt{5}(2 + \sqrt{5})$ \hspace{30mm} (2) $(\sqrt{18} - \sqrt{6}) \div \sqrt{6}$ 

\vspace{20mm}

(3) $(\sqrt{6} + 3)(\sqrt{6} - 1)$ \hspace{30mm} (4) $(\sqrt{5} - 2)^2$

\vspace{20mm}

(5) $(\sqrt{7} + 3)(\sqrt{7} - 3)$

\hspace{20mm}

\question 次の(1) 〜 (4) の下線部の誤りをなおして正しくしなさい。

(1) 64の平方根は\underline{8}である。 \hspace{20mm} (2) $\sqrt{900}$は\underline{$\pm30$}である。

\vspace{20mm}

(3) $\sqrt{(-7)^2}$は\underline{$-7$}である。 \hspace{20mm} (4) $\sqrt{2} + \sqrt{8} = \underline{\sqrt{10}}$

\vspace{20mm}

\question 次の大小関係にあてはまる自然数$a$を、すべて求めなさい。

(1) $2 < \sqrt{a} < 3$ \hspace{40mm} (2) $9 < \sqrt{a} < 9.2$

\vspace{20mm}

\question 次の数を、小さい方から順に並べなさい。

$$
\dfrac{2}{3}, \, \sqrt{\dfrac{2}{3}}, \, \dfrac{\sqrt{2}}{3}, \, \dfrac{2}{\sqrt{3}}
$$
\vspace{8mm}

\question 次の数の分母を有理化しなさい。

(1) $\dfrac{6}{\sqrt{3}}$ \hspace{20mm} (2) $\dfrac{\sqrt{5}}{\sqrt{2}}$ \hspace{20mm} (3) $\dfrac{1}{4\sqrt{6}}$

\vspace{30mm}

\question 次の計算をしなさい。

(1) $\sqrt{32} \times \sqrt{2}$ \hspace{30mm} (2) $2\sqrt{27} \times \sqrt{12}$

\vspace{30mm}

(3) $7\sqrt{2} \div \sqrt{7}$ \hspace{30mm} (4) $3\sqrt{90} \div \sqrt{15} \div 6\sqrt{2}$

\vspace{20mm} 

(5) $(-\sqrt{14}) \div \sqrt{21} \times \sqrt{75}$ \hspace{30mm} (6) $\sqrt{50} + 2\sqrt{18} - 8\sqrt{2}$

\vspace{20mm}

(7) $\sqrt{75} - \sqrt{3} -2\sqrt{27}$ \hspace{30mm} (8) $5\sqrt{8} - 2\sqrt{12} - 3\sqrt{18}$

\vspace{20mm}

(9) $\dfrac{\sqrt{24}}{3} - \dfrac{2}{\sqrt{6}}$ \hspace{30mm} (10) $\sqrt{\dfrac{3}{2}} - \sqrt{\dfrac{2}{3}}$

\question 次の計算をしなさい。

(1) $(3 + 2\sqrt{2})(3 - 2\sqrt{2})$ \hspace{30mm} (2) $(5\sqrt{2} - 1)^2$

\vspace{20mm}

(3) $(\sqrt{7} - 1)(2\sqrt{7} + 3)$ \hspace{30mm} (4) $(\sqrt{5} -2)(3 -\sqrt{5})$

\vspace{20mm}

(5) $(4 + \sqrt{3})(4 + 2\sqrt{3})$ \hspace{30mm} (6) $(3\sqrt{6} + 2\sqrt{3})(3\sqrt{6} - 2\sqrt{3})$

\vspace{20mm}

\question $\sqrt{60a}$の値が自然数となるような自然数$a$のうち、もっとも小さいものを求めなさい。

\vspace{20mm}

\question $x = \sqrt{3} - \sqrt{2}, \, y = \sqrt{3} + \sqrt{2}$のとき、次の式の値を求めなさい。

(1) $(x + y)^2$ \hspace{30mm} (2) $xy$ \hspace{30mm} (3) $x^2 - y^2$

\vspace{20mm}

\question $1, \, 2, \, 3, \,4$のうち、$x^2 - 4x + 3 = 0$の解であるものをすべて選びなさい。

\vspace{15mm}

\question 次の2次方程式を解きなさい。

(1) $4x^2 = 25$ \hspace{30mm} (2) $2x^2 - 20 = 0$

\vspace{20mm}

(3) $(x - 4)^2 = 49$ \hspace{30mm} (4) $(x + 2)^2 = 11$

\vspace{20mm}

\question 次の2次方程式を解きなさい。
\setcounter{skaunta}{0}

\squestion $x^2 +x -1 = 0$ \hspace{30mm} \squestion $5x^2 -7x +2 = 0$

\vspace{30mm}

\squestion $x^2 -4x +2 = 0$ \hspace{30mm} \squestion $3(x^2 + 3x) = -5$

\vspace{30mm}

\squestion $(x - 2)(x + 8) = 0$ \hspace{30mm} \squestion $x^2 -10x -24 = 0$

\vspace{30mm}

\squestion $x^2 - 7x + 12 = 0$ \hspace{30mm} \squestion $x^2 + 3x = 0$

\vspace{30mm}

\squestion $x^2 -4x +4 = 0$ \hspace{30mm} \squestion $x^2 +10x +25 = 0$

\vspace{30mm}

\squestion $2(x^2 - 9x) = x^2 - 9x - 18$ \hspace{40mm} \squestion $x(1 - x) = -20$

\vspace{40mm}

\question 2次方程式$x^2 -ax +5 = 0$の解の1つが5であるとき、$a$の値を求めなさい。また、もう1つの解を求めなさい。

\columnbreak

　


















































































































\end{multicols}
