---
output:
  pdf_document:
    latex_engine: lualatex
    toc: false
    toc_depth: 2
    number_sections: TRUE
header-includes:
  - \usepackage{indentfirst}
  - \parindent = 1em
  - \usepackage{dcolumn}
  - \newcolumntype{.}{D{.}{.}{-1}}
  - \usepackage{caption}
  - \captionsetup[table]{name=表}
  - \captionsetup[figure]{name=図}
  - \usepackage{hyperref}
  - \pagestyle{empty}
  - \usepackage{multicol}
  - \usepackage{ascmac}
  - \setpagelayout*{top=10truemm,bottom=20truemm,left=25truemm,right=10truemm}
  - \usepackage{tikz}
  - \usepackage{tabstackengine}
  - \usepackage{xcolor}
  - \usepackage{rotating}
  - \usepackage{txfonts}
  - \usepackage{fancybox}
  - \usepackage{dashbox}
  - \usepackage{tcolorbox}
  - \usepackage{siunitx}
documentclass: bxjsarticle
classoption: 11pt,b4paper,landscape,lualatex,ja=standard
---

```{r global_option, include = FALSE}
knitr::opts_chunk$set(warning = FALSE, 
                      echo = FALSE, 
                      message = FALSE,
                      fig.width = 7,
                      fig.height = 5)
if (knitr::is_latex_output()) {
  knitr::opts_chunk$set(dev = "cairo_pdf")
}
```
\renewcommand{\thefootnote}{}
\newcounter{kaunta}
\renewcommand{\thekaunta}{\arabic{kaunta}}
\newcommand{\kaunta}{\refstepcounter{kaunta}%
\thekaunta}
\def\question{\noindent\fbox{\large\makebox[1em]{\text{\kaunta}}} \hspace{1pt}}
\newcounter{skaunta}
\renewcommand{\theskaunta}{\arabic{skaunta}}
\newcommand{\skaunta}{\refstepcounter{skaunta}%
\theskaunta}
\def\squestion{(\text{\skaunta})\hspace{2.5pt}}

\begin{flushleft}
\noindent
\large
2次方程式の解き方No.2
\end{flushleft}

\begin{flushright}
名前（\hspace{50mm}）
\end{flushright}

\vspace{1mm}
\hrule

\begin{multicols}{2}

\begin{itembox}[l]{2次方程式の解の公式}
2次方程式$ax^2 + bx + c = 0$の解は
$$
\Large
x = \dfrac{\phantom{-b \pm \sqrt{b^2 - 4ac}}}{\phantom{2a}}
$$
\vspace{1mm}
\end{itembox}

例1. $2x^2 -3x -1 = 0$を、解の公式を使って解きなさい。

$a = $ \hspace{15mm} $b = $ \hspace{15mm} $c = $

\vspace{40mm}

問1. $3x^2 + 7x + 1 = 0$について、次の問に答えなさい。

(1) 解の公式を使って解くとき、$a, \, b, \, c$のそれぞれにどんな値を代入すればよいですか。

\vspace{5mm}

(2) この方程式を解きなさい。

\vspace{40mm}


問2. 次の方程式を解きなさい。

(1) $2x^2 -7x +4 =0$ \hspace{30mm} (2) $4x^2 + x -2 =0$

\vspace{40mm}

\columnbreak
(3) $x^2 - 11x -1 = 0$ \hspace{30mm} (4) $5x^2 - 5x -1 = 0$

\vspace{40mm}



例2. $x^2 + 4x -2 = 0$を解きなさい。

\vspace{40mm}

問3. 次の方程式を解きなさい。

(1) $3x^2 + 4x - 2 = 0$ \hspace{30mm} (2) $2x^2 -4x -5 = 0$

\vspace{40mm}

例3. $2x^2 + 5x -3 = 0$を解きなさい。

\vspace{40mm}









\end{multicols}


























































































