---
output:
  pdf_document:
    latex_engine: lualatex
    toc: false
    toc_depth: 2
    number_sections: TRUE
header-includes:
  - \usepackage{indentfirst}
  - \parindent = 1em
  - \usepackage{dcolumn}
  - \newcolumntype{.}{D{.}{.}{-1}}
  - \usepackage{caption}
  - \captionsetup[table]{name=表}
  - \captionsetup[figure]{name=図}
  - \usepackage{hyperref}
  - \pagestyle{empty}
  - \setpagelayout*{top=10truemm,bottom=10truemm,left=10truemm,right=10truemm}
  - \usepackage{multicol}
  - \usepackage{ascmac}
  - \usepackage{answerbox}
documentclass: bxjsarticle
classoption: 11pt,b4paper,landscape,lualatex,ja=standard
---
```{r global_option, include = FALSE}
knitr::opts_chunk$set(warning = FALSE, 
                      echo = FALSE, 
                      message = FALSE,
                      fig.width = 7,
                      fig.height = 5)
if (knitr::is_latex_output()) {
  knitr::opts_chunk$set(dev = "cairo_pdf")
}
```
\renewcommand{\thefootnote}{}
\newcounter{kaunta}
\renewcommand{\thekaunta}{\arabic{kaunta}}
\newcommand{\kaunta}{\refstepcounter{kaunta}%
\thekaunta}
\def\question{\noindent\fbox{\large\makebox[1em]{\text{\kaunta}}} \hspace{1pt}}
\newcounter{skaunta}
\renewcommand{\theskaunta}{\arabic{skaunta}}
\newcommand{\skaunta}{\refstepcounter{skaunta}%
\theskaunta}
\def\squestion{(\text{\skaunta})\hspace{2.5pt}}
\newcommand{\maru}[1]{\raise0.2ex\hbox{\textcircled{\scriptsize{#1}}}}
\newcommand{\jsim}{\mathrel{\text{∽}}}
\newcommand{\jpara}{/\!/}

\newcounter{kcounter}
\setcounter{kcounter}{0}
\newcommand{\kana}{\refstepcounter{kcounter}\ifthenelse{\value{kcounter}=1}{ア}{\ifthenelse{\value{kcounter}=2}{イ}{\ifthenelse{\value{kcounter}=3}{ウ}{\ifthenelse{\value{kcounter}=4}{エ}{\ifthenelse{\value{kcounter}=5}{オ} {\ifthenelse{\value{kcounter}=6}{カ}{\ifthenelse{\value{kcounter}=7}{キ}{\ifthenelse{\value{kcounter}=8}{ク}{\ifthenelse{\value{kcounter}=9}{ケ}{\ifthenelse{\value{kcounter}=10}{コ}{\ifthenelse{\value{kcounter}=11}{サ}{\ifthenelse{\value{kcounter}=12}{シ}{\ifthenelse{\value{kcounter}=13}{ス}{\ifthenelse{\value{kcounter}=14}{セ}{\ifthenelse{\value{kcounter}=15}{ソ}{\ifthenelse{\value{kcounter}=16}{タ}{\ifthenelse{\value{kcounter}=17}{チ}{\ifthenelse{\value{kcounter}=18}{ツ}{\ifthenelse{\value{kcounter}=19}{テ}{\ifthenelse{\value{kcounter}=20}{ト}{\ifthenelse{\value{kcounter}=21}{ナ}{\ifthenelse{\value{kcounter}=22}{二}{\ifthenelse{\value{kcounter}=23}{ヌ}{\ifthenelse{\value{kcounter}=24}{ネ}{\ifthenelse{\value{kcounter}=25}{ノ}{\ifthenelse{\value{kcounter}=26}{ハ}{\ifthenelse{\value{kcounter}=27}{ヒ}{\ifthenelse{\value{kcounter}=28}{フ}{\ifthenelse{\value{kcounter}=29}{ヘ}{\ifthenelse{\value{kcounter}=30}{ホ}{\ifthenelse{\value{kcounter}=31}{マ}{\ifthenelse{\value{kcounter}=32}{ミ}{\ifthenelse{\value{kcounter}=33}{ム}{\ifthenelse{\value{kcounter}=34}{メ}{\ifthenelse{\value{kcounter}=35}{モ}{\ifthenelse{\value{kcounter}=36}{ヤ}{\ifthenelse{\value{kcounter}=37}{ユ}{\ifthenelse{\value{kcounter}=38}{ヨ}{\ifthenelse{\value{kcounter}=39}{ラ}{\ifthenelse{\value{kcounter}=40}{リ}{\ifthenelse{\value{kcounter}=41}{ル}{\ifthenelse{\value{kcounter}=42}{レ}{\ifthenelse{\value{kcounter}=43}{ロ}{\ifthenelse{\value{kcounter}=44}{ワ}{・}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}

\newcommand{\kuran}[1]{\framebox[1.5cm][c]{\maru{#1}}}

\newcommand{\tokuten}{%
\begin{flushright}%
\begin{tabular}{@{}r}%
\begin{tikzpicture}%
  \draw (-.5, 0) rectangle (2.5, 2);%
  \draw (2.5, 0) rectangle (5.5, 2);%
  \draw (5.5, 0) rectangle (9, 2);%
  \draw (1, -0.3) node[inner sep=1pt, fill=white]{\footnotesize{知・技}};%
  \draw (4, -0.3) node[inner sep=1pt, fill=white]{\footnotesize{思・判・表}};%
  \draw (7.2, -0.3) node[inner sep=1pt, fill=white]{\footnotesize{合計}};%
\end{tikzpicture}%
\end{tabular}%
\end{flushright}%
}

\answerbox{Swidth=10mm}

\large
1年生数学科2学期期末テスト 解答用紙\maru{1}

\begin{flushright}
組(\hspace{5mm})\hspace{1pt}番号(\hspace{5mm})\hspace{1pt}名前(\hspace{50mm})
\end{flushright}

\hrule

\begin{multicols}{2}

\begin{ansbox}
\schg{ア}
\pbox[4]{12}
\end{ansbox}

\begin{ansbox}
\pbox*{1}
\end{ansbox}

\begin{ansbox}
\pbox[2]{4}
\end{ansbox}

\begin{multicols}{2}

\begin{ansbox}
\schg{A}
\pbox{1}
\pbox{1}
\pbox{1}
\pbox{1}
\end{ansbox}

\columnbreak

\begin{ansbox*}
\schg{(1)}
\pbox{1}[height=70mm]
\ptxt{1}{c}{%
\begin{tikzpicture}[scale=0.45]%
\draw[help lines] (-6,-6) grid (6,6);%
\draw[thick](-6,0) -- (6,0)node[right]{$x$};%
\draw[thick](0,-6) -- (0,6)node[above]{$y$};%
\draw (0,0) node[below left]{O};%
\foreach \x in {-4, -2, 2, 4} \draw ({\x},0) node[below]{$\x$};%
\foreach \y in {-4, -2, 2, 4} \draw (0,{\y}) node[right]{$\y$};%
\end{tikzpicture}%
}
\end{ansbox*}
\end{multicols}

\columnbreak

\begin{ansbox}
\pbox*[2]{8}
\ptxt{1}{l}{（比例）}
\ptxt{2}{l}{（式）}
\ptxt{3}{l}{（比例）}
\ptxt{4}{l}{（式）}
\ptxt{5}{l}{（反比例）}
\ptxt{6}{l}{（式）}
\ptxt{7}{l}{（反比例）}
\ptxt{8}{l}{（式）}
\end{ansbox}

\begin{ansbox}
\pbox[2]{2}[height=22mm]
\pbox[2]{2}
\ptxt{2}{c}{%
\begin{tabular}{c|ccccccc}%
\hline%
$x$ & $\cdots$ & $-4$ & $0$ & $4$ & $\cdots$ & $12$ & $\cdots$ \\%
\hline%
$y$ & $\cdots$ &  &  &  & $\cdots$ & & $\cdots$ \\%
\hline%
\end{tabular}%
}
\end{ansbox}

\begin{ansbox}
\pbox[2]{2}[height=22mm]
\pbox[2]{2}
\ptxt{2}{c}{%
\begin{tabular}{c|ccccccc}%
\hline%
$x$ & $\cdots$ & $-4$ & $0$ & $4$ & $\cdots$ & $12$ & $\cdots$ \\%
\hline%
$y$ & $\cdots$ &  & $\times$ &  & $\cdots$ & & $\cdots$ \\%
\hline%
\end{tabular}%
}
\end{ansbox}

\begin{multicols}{2}
\begin{ansbox}
\pbox{1}
\sxchg{2}{3}
\pbox{1}
\end{ansbox}

\columnbreak

\begin{ansbox*}
\pbox{1}[shoumon=2,height=65mm]
\ptxt{2}{c}{%
\begin{tikzpicture}[scale=0.45]%
\draw[help lines] (-6,-6) grid (6,6);%
\draw[thick](-6,0) -- (6,0)node[right]{$x$};%
\draw[thick](0,-6) -- (0,6)node[above]{$y$};%
\draw(0,0) node[below left]{O};%
\foreach \x in {-4, -2, 2, 4} \draw ({\x},0) node[below]{$\x$};%
\foreach \y in {-4, -2, 2, 4} \draw (0,{\y}) node[right]{$\y$};%
\fill (-5,4) circle[radius=5pt] node[above left]{A};%
\begin{scope}\clip(-6,-6) rectangle (6,6);%
\draw [samples=100, smooth, thick, domain=-6:6] plot(\x, {6/\x});%
\end{scope}%
\end{tikzpicture}%
}
\end{ansbox*}

\end{multicols}

\end{multicols}

\newpage

\large
1年生数学科2学期期末テスト 解答用紙\maru{2}

\begin{flushright}
組(\hspace{5mm})\hspace{1pt}番号(\hspace{5mm})\hspace{1pt}名前(\hspace{50mm})
\end{flushright}

\hrule

\begin{multicols}{2}

\begin{ansbox}
\pbox*{1}
\end{ansbox}

\begin{ansbox}
\pbox*{1}
\pbox*{1}[height=30mm]
\ptxt{1}{c}{分後}
\ptxt{2}{l}{（理由）}
\end{ansbox}

\vspace{10mm}

\begin{ansbox}
\pbox{1}
\ptxt{1}{c}{は\hspace{30mm}の関数である}
\pbox{1}
\ptxt{2}{l}{（記号）}
\pbox*{1}[height=40mm]
\ptxt{3}{l}{（理由）}
\end{ansbox}

\vspace{10mm}

\tokuten

\columnbreak

\phantom{空白}

\end{multicols}








































