---
output:
  pdf_document:
    latex_engine: lualatex
    toc: false
    toc_depth: 2
    number_sections: TRUE
header-includes:
  - \usepackage{indentfirst}
  - \parindent = 0pt
  - \usepackage{dcolumn}
  - \newcolumntype{.}{D{.}{.}{-1}}
  - \usepackage{caption}
  - \captionsetup[table]{name=表}
  - \captionsetup[figure]{name=図}
  - \usepackage{hyperref}
  - \pagestyle{empty}
  - \usepackage{multicol}
  - \usepackage{ascmac}
  - \usepackage{tikz}
  - \usepackage{amsmath}
  - \usepackage{amsfonts}
  - \usepackage{latexsym}
  - \usepackage{graphics}
  - \usepackage{here}
documentclass: bxjsarticle
classoption: 11pt,a4paper,lualatex,ja=standard
---

```{r global_option, include = FALSE}
knitr::opts_chunk$set(warning = FALSE, 
                      echo = FALSE, 
                      message = FALSE,
                      fig.width = 7,
                      fig.height = 5)
if (knitr::is_latex_output()) {
  knitr::opts_chunk$set(dev = "cairo_pdf")
}
```

\renewcommand{\thefootnote}{}
\newcounter{kaunta}
\renewcommand{\thekaunta}{\arabic{kaunta}}
\newcommand{\kaunta}{\refstepcounter{kaunta}%
\thekaunta}
\def\question{\noindent\fbox{\large\makebox[1em]{\text{\kaunta}}} \hspace{1pt}}
\newcounter{skaunta}
\renewcommand{\theskaunta}{\arabic{skaunta}}
\newcommand{\skaunta}{\refstepcounter{skaunta}%
\theskaunta}
\def\squestion{(\text{\skaunta})\hspace{2.5pt}}

\begin{flushleft}
\noindent
\large
調べてみよう
\end{flushleft}

\begin{flushright}
名前（\hspace{50mm}）
\end{flushright}

\vspace{1mm}
\hrule

\begin{itembox}[l]{Q}
等式$10x + 1000 = 2100$で、$x$の値が1800, 1900, 2000, 2100, 2200のときの左辺の値を求め、右辺の値と比べてみましょう。
\end{itembox}

\renewcommand{\arraystretch}{2.0}

\vspace{20mm}

\begin{table}[!h]
\centering
\begin{tabular}{|c|c|c|c|}
\hline
$x$の値 & 左辺の値 & & 右辺の値 \\
\hline
1800 & \phantom{$10 \times 1800 + 1000$}\phantom{$10 \times 1800 + 1000$} & \phantom{$<<<<$} & \phantom{21000}\phantom{21000} \\
\hline
1900 & \phantom{$10 \times 1800 + 1000$}\phantom{$10 \times 1800 + 1000$} & \phantom{$<<<<$} & \phantom{21000}\phantom{21000} \\
\hline
2000 & \phantom{$10 \times 1800 + 1000$}\phantom{$10 \times 1800 + 1000$} & \phantom{$<<<<$} & \phantom{21000}\phantom{21000} \\
\hline
2100 & \phantom{$10 \times 1800 + 1000$}\phantom{$10 \times 1800 + 1000$} & \phantom{$<<<<$} & \phantom{21000}\phantom{21000} \\
\hline
2200 & \phantom{$10 \times 1800 + 1000$}\phantom{$10 \times 1800 + 1000$} & \phantom{$<<<<$} & \phantom{21000}\phantom{21000} \\
\hline
\end{tabular}
\end{table}





























