---
output:
  pdf_document:
    latex_engine: lualatex
    toc: false
    toc_depth: 2
    number_sections: TRUE
header-includes:
  - \usepackage{indentfirst}
  - \parindent = 0em
  - \usepackage{dcolumn}
  - \newcolumntype{.}{D{.}{.}{-1}}
  - \usepackage{caption}
  - \captionsetup[table]{name=表}
  - \captionsetup[figure]{name=図}
  - \usepackage{hyperref}
  - \pagestyle{empty}
  - \usepackage{multicol}
  - \usepackage{ascmac}
  - \setpagelayout*{top=10truemm,bottom=20truemm,left=25truemm,right=10truemm}
  - \usepackage{tikz}
  - \usepackage{tabstackengine}
  - \usepackage{xcolor}
  - \usepackage{rotating}
  - \usepackage{txfonts}
  - \usepackage{fancybox}
  - \usepackage{dashbox}
  - \usepackage{tcolorbox}
  - \usepackage{siunitx}
documentclass: bxjsarticle
classoption: 11pt,b4paper,landscape,lualatex,ja=standard
---

```{r global_option, include = FALSE}
knitr::opts_chunk$set(warning = FALSE, 
                      echo = FALSE, 
                      message = FALSE,
                      fig.width = 7,
                      fig.height = 5)
if (knitr::is_latex_output()) {
  knitr::opts_chunk$set(dev = "cairo_pdf")
}
```
\renewcommand{\thefootnote}{}
\newcounter{kaunta}
\renewcommand{\thekaunta}{\arabic{kaunta}}
\newcommand{\kaunta}{\refstepcounter{kaunta}%
\thekaunta}
\def\question{\noindent\fbox{\large\makebox[1em]{\text{\kaunta}}} \hspace{1pt}}
\newcounter{skaunta}
\renewcommand{\theskaunta}{\arabic{skaunta}}
\newcommand{\skaunta}{\refstepcounter{skaunta}%
\theskaunta}
\def\squestion{(\text{\skaunta})\hspace{2.5pt}}

\begin{flushleft}
\noindent
\large
1次方程式100本ノック
\end{flushleft}

\begin{flushright}
名前（\hspace{50mm}）
\end{flushright}

\vspace{1mm}
\hrule

\begin{multicols}{2}
\question 次の方程式を等式の性質を使って解きなさい。

\squestion $x - 3 = 23$ \hfill \squestion $x + 15 = 11$ \hfill \squestion $7 + x = 30$

\vspace{25mm}

\squestion $-5 + x = 3$ \hfill \squestion $4x = -12$ \hfill \squestion $-7x = -35$

\vspace{25mm}

\squestion $\dfrac{x}{3} = 5$ \hfill \squestion $\dfrac{1}{8}x = -\dfrac{3}{4}$ \hfill \squestion $\dfrac{3}{5}x = -6$

\vspace{25mm}

\squestion $x + 1.6 = -1.9$ \hfill \squestion $0.2x = -12$ \hfill \squestion $\dfrac{1}{4} + x = -\dfrac{1}{2}$

\vspace{25mm}

\question 次の方程式を解きなさい。

\squestion $5x + 8 = 23$ \hfill \squestion $6x -5 = -17$ \hfill \squestion $-2x + 3 = 5$

\vspace*{25mm}

\columnbreak

\squestion $-4x + 19 = 11$ \hfill \squestion $10x = 6x - 8$ \hfill \squestion $3x = 5x - 15$ 

\vspace{25mm}

\squestion $4x = 50 - 6x$ \hfill \squestion $-8x = 3 -5x$ \hfill \squestion $9x + 2 = 4x + 17$ 

\vspace{25mm} 

\squestion $5x - 8 = -17 -4x$ \hfill \squestion $1 - x = 5x -2$ \hfill \squestion $12x - 3 = 7x - 3$ 

\vspace{25mm} 

\squestion $4x + 1 = 3(x + 2)$ \hfill \squestion $7(x - 4) = 3x + 8$ \hfill \squestion $-4(x + 3) = 5(x - 6)$ 

\vspace{25mm} 

\squestion $5 - 2(7x - 2) = 1$ \hfill \squestion $\dfrac{x + 1}{3} = \dfrac{1}{4}x + 1$ \hfill \squestion $\dfrac{9x - 5}{6} = \dfrac{8 + x}{3}$

\vspace{25mm}

\squestion $x + \dfrac{x - 1}{3} = 3$ \hfill \squestion $0.3x + 2 = 0.1x + 1.6$ \hfill \squestion $800x = 2400(x - 2)$ 

\vspace{25mm}

\newpage

\end{multicols}

\begin{flushleft}
\noindent
\large
1次方程式100本ノック
\end{flushleft}

\begin{flushright}
名前（\hspace{50mm}）
\end{flushright}

\vspace{1mm}
\hrule

\begin{multicols}{2}

\squestion $0.5x - 2.5 = -x + 2$ \hfill \squestion $0.2x - 0.03 = 0.3x + 0.07$ \hfill \squestion $3x = 21$

\vspace{25mm}

\squestion $17x = 17$ \hfill \squestion $\dfrac{4}{5}x = 8$ \hfill \squestion $18 = -2x$

\vspace{25mm} 

\squestion $6x - 11 = 7$ \hfill \squestion $6 -2x = 12$ \hfill \squestion $4x -9 = 3x -15$

\vspace{25mm}

\squestion $x - 17 = -7 - 3x$ \hfill \squestion $9x -70 = 6x + 80$ \hfill \squestion $8 + 4x = 10x + 16$

\vspace{25mm}

\squestion $3x -1200 = 1200 + 9x$ \hfill \squestion $-18 + 5x = 12x -18$ \hfill \squestion $2(x + 1) = x + 3$

\vspace{25mm}

\squestion $3(x - 8) = 9(4 - x)$ \hfill \squestion $-3(2x - 4) = 5(x - 2)$ \hfill \squestion $80 -30(x - 5) = 110$

\vspace*{25mm}

\columnbreak

\squestion $0.1x = 0.4(x - 2) - 0.1$ \hfill \squestion $\dfrac{1}{4}x - 1 = \dfrac{1}{2}x$ \hfill \squestion $\dfrac{2x - 7}{3} = \dfrac{x + 1}{2}$

\vspace{25mm}

\squestion $5 + \dfrac{3}{100}x = \dfrac{7}{100}x$ \hfill \squestion $x : 21 = 3 :7 $ \hfill \squestion $15 : 6 = x : 8$

\vspace{25mm}

\squestion $9 : 4 = 2 : x$ \hfill \squestion $(x + 2) : x = 5 : 3$ \hfill \squestion $3 : 12 = x : 36$

\vspace{25mm}

\squestion $12 : x = 4 : 7$ \hfill \squestion $x : \dfrac{1}{2} = 4 : \dfrac{15}{2}$ \hfill \squestion $x : 3 = (x + 3) : 4$

\vspace{25mm}

\squestion $x - 5 = 8$ \hfill \squestion $x - 7 = -5$ \hfill \squestion $x + 13 = 4$

\vspace*{25mm}

\squestion $x + 6 = -4$ \hfill \squestion $3x = -12$ \hfill \squestion $5x = 35$

\vspace*{25mm}

\end{multicols}

\newpage

\begin{flushleft}
\noindent
\large
1次方程式100本ノック
\end{flushleft}

\begin{flushright}
名前（\hspace{50mm}）
\end{flushright}

\vspace{1mm}
\hrule

\begin{multicols}{2}

\squestion $\dfrac{1}{3}x = \dfrac{1}{2}$ \hfill \squestion $\dfrac{2}{3}x = -6$ \hfill \squestion $4x + 10 = 2$

\vspace{25mm} 

\squestion $2x - 3 = 5$ \hfill \squestion $5x = x -4$ \hfill \squestion $10x = 7x + 6$

\vspace{25mm}

\squestion $3x + 5 = x + 11$ \hfill \squestion $4(x - 3) = 3x -2$ \hfill \squestion $x - 1 = \dfrac{x - 1}{3}$

\vspace{25mm}

\squestion $0.4x + 0.7 = 0.1x - 0.2$ \hfill \squestion $x : 4 = 6 : 3$ \hfill \squestion $2 : x = 4 : 8$ 

\vspace{25mm}

\squestion $x : (x + 3) = 3:4$ \hfill \squestion $3x : (x + 2) = 9 : 5$ \hfill \squestion $4x + 2 = 5x - 9$ 

\vspace{25mm}

\squestion $33 - x = x + 49$ \hfill \squestion $-5 + 19x = 4x -5$ \hfill \squestion $24x + 8 = 9x -22$ 

\vspace*{25mm}

\columnbreak

\squestion $3000 - 11x = 2400 -5x$ \hfill \squestion $230 + 47x = 610 + 28x$ \hfill \squestion $5(x - 8) = x$ 

\vspace*{25mm}

\squestion $x - 2(3x + 1) = 18$ \hfill \squestion $3(3x + 2) = -6(2 -x)$ \hfill \squestion $4(t - 1) + 3(3t + 5) = 2t$ 

\vspace{25mm}

\squestion $\dfrac{2}{5}x - 3 = \dfrac{3}{10}x + \dfrac{1}{2}$ \hfill \squestion $\dfrac{3y -1}{4} = \dfrac{2y - 3}{3}$ \hfill \squestion $0.3(x + 1) = 0.2x$ 

\vspace{25mm}

\squestion $1.2x + 3.1 = 0.8x + 0.3$ \hfill \squestion $600x + 2400 = 1000x$ \hfill \squestion $30(-x + 2) + 120 = 240$

\vspace{25mm}

\squestion $x : 15 = 3 : 5$ \hfill \squestion $12 : 9 = x :12$ \hfill \squestion $7.2 : 2.4 = 60 : x$

\vspace{25mm}

\squestion $4 : x = \dfrac{1}{2} : \dfrac{5}{3}$ \hfill \squestion $x : (10 - x) = 2 : 3$ \hfill \squestion $(x - 4) : 3 = x : 4$

\end{multicols}




















































