---
output:
  pdf_document:
    latex_engine: lualatex
    toc: false
    toc_depth: 2
    number_sections: TRUE
header-includes:
  - \usepackage{indentfirst}
  - \parindent = 1em
  - \usepackage{dcolumn}
  - \newcolumntype{.}{D{.}{.}{-1}}
  - \usepackage{caption}
  - \captionsetup[table]{name=表}
  - \captionsetup[figure]{name=図}
  - \usepackage{hyperref}
  - \pagestyle{empty}
  - \usepackage{multicol}
  - \usepackage{ascmac}
  - \setpagelayout*{top=15truemm}
  - \usepackage{tikz}
  - \usepackage{tabstackengine}
  - \usepackage{xcolor}
  - \usepackage{rotating}
  - \usepackage{txfonts}
  - \usepackage{fancybox}
  - \usepackage{dashbox}
  - \usepackage{tcolorbox}
documentclass: bxjsarticle
classoption: 11pt,a4paper,lualatex,ja=standard
---

```{r global_option, include = FALSE}
knitr::opts_chunk$set(warning = FALSE, 
                      echo = FALSE, 
                      message = FALSE,
                      fig.width = 7,
                      fig.height = 5)
if (knitr::is_latex_output()) {
  knitr::opts_chunk$set(dev = "cairo_pdf")
}
```
\renewcommand{\thefootnote}{}
\newcounter{kaunta}
\renewcommand{\thekaunta}{\arabic{kaunta}}
\newcommand{\kaunta}{\refstepcounter{kaunta}%
\thekaunta}
\def\question{\noindent\fbox{\large\makebox[1em]{\text{\kaunta}}} \hspace{1pt}}
\newcounter{skaunta}
\renewcommand{\theskaunta}{\arabic{skaunta}}
\newcommand{\skaunta}{\refstepcounter{skaunta}%
\theskaunta}
\def\squestion{(\text{\skaunta})\hspace{2.5pt}}

\begin{flushleft}
\noindent
\large
基本の問題
\end{flushleft}

\begin{flushright}
名前（\hspace{50mm}）
\end{flushright}

\vspace{1mm}
\hrule

\question 次の数の平方根をいいなさい。

\squestion 6 \hspace{10mm} \squestion 36 \hspace{10mm} 
\squestion 400 \hspace{10mm} \squestion $\dfrac{5}{3}$

\vspace{15mm}

\setcounter{skaunta}{0}
\question 次の数を根号を使わずに表しなさい。

\squestion $\sqrt{64}$ \hspace{10mm} \squestion $-\sqrt{100}$ \hspace{10mm}
\squestion $\sqrt{(-11)^2}$ \hspace{10mm} \squestion $\sqrt{0.49}$ \hspace{10mm} \squestion $(-\sqrt{3})^2$

\vspace{20mm}

\setcounter{skaunta}{0}
\question 次の各組の数の大小を、不等号を使って表しなさい。

\squestion $\sqrt{61}, \, \sqrt{70}$ \hspace{15mm} 
\squestion $5, \, \sqrt{23}$

\vspace{15mm}

\question 次の数の中から、無理数を選びなさい。

ア. 3　\hspace{10mm} イ. $-1.2$ \hspace{10mm} ウ. $-\sqrt{15}$ \hspace{10mm}
エ. $\sqrt{81}$ \hspace{10mm} オ. $\dfrac{1}{6}$























