---
output:
  pdf_document:
    latex_engine: lualatex
    toc: false
    toc_depth: 2
    number_sections: TRUE
header-includes:
  - \usepackage{indentfirst}
  - \parindent = 0em
  - \usepackage{dcolumn}
  - \newcolumntype{.}{D{.}{.}{-1}}
  - \usepackage{caption}
  - \captionsetup[table]{name=表}
  - \captionsetup[figure]{name=図}
  - \usepackage{hyperref}
  - \pagestyle{empty}
  - \usepackage{multicol}
  - \usepackage{ascmac}
  - \setpagelayout*{top=10truemm,bottom=20truemm,left=25truemm,right=10truemm}
  - \usepackage{tikz}
  - \usepackage{tabstackengine}
  - \usepackage{xcolor}
  - \usepackage{rotating}
  - \usepackage{txfonts}
  - \usepackage{fancybox}
  - \usepackage{dashbox}
  - \usepackage{tcolorbox}
  - \usepackage{siunitx}
documentclass: bxjsarticle
classoption: 11pt,a4paper,lualatex,ja=standard
---

```{r global_option, include = FALSE}
knitr::opts_chunk$set(warning = FALSE, 
                      echo = FALSE, 
                      message = FALSE,
                      fig.width = 7,
                      fig.height = 5)
if (knitr::is_latex_output()) {
  knitr::opts_chunk$set(dev = "cairo_pdf")
}
```
\renewcommand{\thefootnote}{}
\newcounter{kaunta}
\renewcommand{\thekaunta}{\arabic{kaunta}}
\newcommand{\kaunta}{\refstepcounter{kaunta}%
\thekaunta}
\def\question{\noindent\fbox{\large\makebox[1em]{\text{\kaunta}}} \hspace{1pt}}
\newcounter{skaunta}
\renewcommand{\theskaunta}{\arabic{skaunta}}
\newcommand{\skaunta}{\refstepcounter{skaunta}%
\theskaunta}
\def\squestion{(\text{\skaunta})\hspace{2.5pt}}

\begin{flushleft}
\noindent
\large
計算練習
\end{flushleft}

\begin{flushright}
名前（\hspace{50mm}）
\end{flushright}

\vspace{1mm}
\hrule

\question 次の式を、文字式の表し方にしたがって表しなさい。

\squestion $y \times 6 \times \x$

\vfill

\squestion $(a + b) \times 6$

\vfill

\squestion $y \times \dfrac{4}{5}$

\vfill

\squestion $a \times (-1)$

\vfill

\squestion $(-5) \times c$

\vfill

\squestion $x \times 3 + y \times 0.1$

\vfill

\squestion $b \times b \times b \times b$

\vfill

\squestion $a \times a \times (-7)$

\vfill

\squestion $9 + 1 \times x \times y \times x \times x$

\vfill

\squestion $2x \div 9$

\vfill

\squestion $(x - y) \div 3$

\vfill

\squestion $a \div (-4)$

\vfill

































































